/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/coach/thread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thread */
        get: operations["get_thread_api_coach_thread_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Turn */
        post: operations["post_turn_api_coach_turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Review */
        post: operations["post_review_api_coach_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/review/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schema */
        get: operations["get_schema_api_coach_review_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/review/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Validate */
        post: operations["post_validate_api_coach_review_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/review/yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Yaml */
        get: operations["get_yaml_api_coach_review_yaml_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Sync */
        post: operations["post_sync_api_jobs_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Checkin */
        post: operations["post_checkin_api_jobs_checkin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Memory */
        get: operations["get_memory_api_coach_memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/memory/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Forget */
        delete: operations["forget_api_coach_memory__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset */
        post: operations["reset_api_coach_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Today */
        get: operations["get_today_api_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CheckinIn */
        CheckinIn: {
            /**
             * Sync
             * @default true
             */
            sync: boolean;
        };
        /**
         * FuelOut
         * @description target null: "No targets yet, ask the coach".
         */
        FuelOut: {
            target: components["schemas"]["TargetOut"] | null;
            /** Targets Through */
            targets_through: string | null;
        };
        /** FuelPlanOut */
        FuelPlanOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Tp Workout Id */
            tp_workout_id: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Violations */
            violations: string[];
            /** Written */
            written: boolean;
        };
        /** GoalOut */
        GoalOut: {
            /** Goal Type */
            goal_type: string;
            /** Event Name */
            event_name: string | null;
            /** Event Date */
            event_date: string | null;
            /** Days To Go */
            days_to_go: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeaderOut */
        HeaderOut: {
            /**
             * Today
             * Format: date
             */
            today: string;
            /** Phase */
            phase: string;
            goal: components["schemas"]["GoalOut"] | null;
            week: components["schemas"]["WeekHeader"];
            /** Last Sync */
            last_sync: components["schemas"]["SyncOut"][];
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed";
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
        };
        /** JobStarted */
        JobStarted: {
            /** Id */
            id: string;
        };
        /**
         * LabsOut
         * @description null with labs_enabled: "No panels stored"; labs_missing: "apply
         *     migrations/005_wellness.sql".
         */
        LabsOut: {
            /** Panel Id */
            panel_id: number;
            /**
             * Drawn On
             * Format: date
             */
            drawn_on: string;
            /** Lab Name */
            lab_name: string | null;
            /** Report On */
            report_on: string | null;
            /** Outside Optimal */
            outside_optimal: number | null;
            /** Markers */
            markers: number | null;
            /** Priorities */
            priorities: string | null;
        };
        /** MemoryEntry */
        MemoryEntry: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "injury" | "constraint" | "preference" | "event" | "coaching_style" | "note" | "checkin";
            /** Text */
            text: string;
            /**
             * Created
             * Format: date
             */
            created: string;
            /** Until */
            until?: string | null;
        };
        /** MemoryOut */
        MemoryOut: {
            /** Entries */
            entries: components["schemas"]["MemoryEntry"][];
            /** Active Ids */
            active_ids: string[];
        };
        /** Readiness */
        Readiness: {
            /** Api Key */
            api_key: boolean;
            /** Checkpointer */
            checkpointer: boolean;
            /** Store */
            store: boolean;
        };
        /**
         * ReadinessOut
         * @description null: "No Garmin data yet, sync first".
         */
        ReadinessOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Is Today */
            is_today: boolean;
            /** Sleep Score */
            sleep_score: number | null;
            /** Sleep Hours */
            sleep_hours: number | null;
            /** Hrv */
            hrv: number | null;
            /** Resting Hr */
            resting_hr: number | null;
            /** Body Battery */
            body_battery: number | null;
            /** Training Readiness */
            training_readiness: number | null;
            /** Ctl */
            ctl: number | null;
            /** Atl */
            atl: number | null;
            /** Tsb */
            tsb: number | null;
        };
        /** ResetIn */
        ResetIn: {
            /**
             * Confirm
             * @constant
             */
            confirm: true;
            /**
             * Forget Memory
             * @default false
             */
            forget_memory: boolean;
        };
        /** ReviewIn */
        ReviewIn: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "reject" | "edit";
            /** Note */
            note?: string | null;
            /** Proposals */
            proposals?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** ReviewPayload */
        ReviewPayload: {
            /** Narration */
            narration: string;
            /** Proposals */
            proposals: {
                [key: string]: unknown;
            }[];
        };
        /** SchemaOut */
        SchemaOut: {
            /** Proposal */
            proposal: {
                [key: string]: unknown;
            };
            /** Planning Change */
            planning_change: {
                [key: string]: unknown;
            };
            /** Nutrition Change */
            nutrition_change: {
                [key: string]: unknown;
            };
        };
        /**
         * SessionOut
         * @description null: "No session planned".
         */
        SessionOut: {
            /** Workouts */
            workouts: components["schemas"]["WorkoutOut"][];
            fuel: components["schemas"]["FuelPlanOut"] | null;
        };
        /** SportCount */
        SportCount: {
            /** Sport */
            sport: string;
            /** Planned */
            planned: number;
            /** Completed */
            completed: number;
        };
        /** StatusOut */
        StatusOut: {
            /** Live */
            live: boolean;
            /** Tools */
            tools: string[];
            ready: components["schemas"]["Readiness"];
            /** Thread */
            thread: string;
            /** Running */
            running: string | null;
        };
        /** SyncIn */
        SyncIn: {
            /** Since */
            since?: string | null;
            /**
             * Full
             * @default false
             */
            full: boolean;
        };
        /** SyncOut */
        SyncOut: {
            /** Source */
            source: string;
            /**
             * Last Synced Date
             * Format: date
             */
            last_synced_date: string;
            /**
             * Last Run At
             * Format: date-time
             */
            last_run_at: string;
            /** Status */
            status: string;
            /** Error */
            error: string | null;
        };
        /** TargetOut */
        TargetOut: {
            /** Day Type */
            day_type: string;
            /** Total Kcal */
            total_kcal: number;
            /** Carbs G */
            carbs_g: number;
            /** Protein G */
            protein_g: number;
            /** Fat G */
            fat_g: number;
            /** Fluid Baseline Ml */
            fluid_baseline_ml: number;
            /** Written To Garmin */
            written_to_garmin: boolean;
        };
        /** ThreadView */
        ThreadView: {
            /** Messages */
            messages: components["schemas"]["UiMessage"][];
            paused: components["schemas"]["ReviewPayload"] | null;
            held: components["schemas"]["ReviewPayload"] | null;
            /** Stuck */
            stuck: boolean;
            /** Running */
            running: string | null;
        };
        /** TodayView */
        TodayView: {
            header: components["schemas"]["HeaderOut"];
            session: components["schemas"]["SessionOut"] | null;
            readiness: components["schemas"]["ReadinessOut"] | null;
            fuel: components["schemas"]["FuelOut"];
            week: components["schemas"]["WeekOut"] | null;
            labs: components["schemas"]["LabsOut"] | null;
            /** Labs Enabled */
            labs_enabled: boolean;
            /** Labs Missing */
            labs_missing: boolean;
            pending?: components["schemas"]["ReviewPayload"] | null;
        };
        /** TurnIn */
        TurnIn: {
            /** Text */
            text: string;
        };
        /** UiMessage */
        UiMessage: {
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "activity" | "consult" | "report";
            /** Text */
            text: string;
            /** Where */
            where?: string | null;
            /** Name */
            name?: string | null;
            /** Args */
            args?: {
                [key: string]: unknown;
            } | null;
            /** Chars */
            chars?: number | null;
        };
        /** ValidateIn */
        ValidateIn: {
            /** Proposals */
            proposals?: {
                [key: string]: unknown;
            }[] | null;
            /** Yaml */
            yaml?: string | null;
        };
        /** Validated */
        Validated: {
            /** Ok */
            ok: boolean;
            /** Proposals */
            proposals?: {
                [key: string]: unknown;
            }[];
            /** Errors */
            errors?: components["schemas"]["ValidationItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationItem */
        ValidationItem: {
            /** Loc */
            loc: (string | number)[];
            /** Msg */
            msg: string;
        };
        /** WeekHeader */
        WeekHeader: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /** Number */
            number: number | null;
            /** Of */
            of: number | null;
        };
        /**
         * WeekOut
         * @description null: "No plan; ask the coach to build one".
         */
        WeekOut: {
            /** Phase */
            phase: string;
            /** Target Hours */
            target_hours: number | null;
            /** Target Tss */
            target_tss: number | null;
            /** Actual Hours */
            actual_hours: number;
            /** Actual Tss */
            actual_tss: number;
            /** Sessions */
            sessions: components["schemas"]["SportCount"][];
        };
        /** WorkoutOut */
        WorkoutOut: {
            /** Tp Workout Id */
            tp_workout_id: string;
            /** Sport */
            sport: string;
            /** Title */
            title: string | null;
            /** Completed */
            completed: boolean;
            /** Planned Duration Sec */
            planned_duration_sec: number | null;
            /** Planned Tss */
            planned_tss: number | null;
            /** Actual Duration Sec */
            actual_duration_sec: number | null;
            /** Actual Tss */
            actual_tss: number | null;
        };
        /** YamlOut */
        YamlOut: {
            /** Yaml */
            yaml: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_thread_api_coach_thread_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadView"];
                };
            };
        };
    };
    post_turn_api_coach_turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_review_api_coach_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_api_coach_review_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaOut"];
                };
            };
        };
    };
    post_validate_api_coach_review_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Validated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_yaml_api_coach_review_yaml_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YamlOut"];
                };
            };
        };
    };
    post_sync_api_jobs_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_checkin_api_jobs_checkin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckinIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_api_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memory_api_coach_memory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryOut"];
                };
            };
        };
    };
    forget_api_coach_memory__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_api_coach_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOut"];
                };
            };
        };
    };
    get_today_api_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayView"];
                };
            };
        };
    };
}
